[package]
name = "grpc_bp_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.13.2"
tokio = { version = "1.40.0", features = ["full"] }
tonic = "0.12.2"


[build-dependencies]
tonic-build = "0.12.2"
