[package]
name = "grpc_bp_rust"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tonic-build = "0.4"

[dependencies]
tonic = "0.4"
prost = "0.7"
tokio = { version = "1", features = ["full"] }
serde = { version ="1.0.210", features = ["derive"] }
serde_yaml = "0.9.34"
